---
name: Issue Template
description: Raise tickets related to the Programme
title: <descriptive title>
body:
  - type: markdown
    attributes:
      value: >
        Make sure you fill in all the fields so your ticket is clear to everyone.
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Explain what and why is needed for this ticket
      placeholder: Think about any context that makes this easier to understand and act on
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Think about the rules, steps or tasks that need to be done in order
        for this ticket to be considered done.
    validations:
      required: true
  - type: input
    id: owner
    attributes:
      label: Owner
      description: Who is responsible for leading and doing this ticket
      placeholder: ex. @kfklein15
    validations:
      required: true
  - type: input
    id: stakeholder
    attributes:
      label: Stakeholder
      description: Who is responsible for giving you input, influence or must be
        informed about it
      placeholder: ex. @kfklein15 - PD
    validations:
      required: true
  - type: input
    id: approver
    attributes:
      label: Approver
      description: Who is approving the final outcome
      placeholder: ex. @kfklein15
    validations:
      required: true
